### ISSUE TITLE
dbvalue function not working with QGIS3

### ISSUE THREAD

**Issue by Isaacson33** [enricofer/refFunctions#14]
All my dbvalue expressions (working in QGIS2.16) are returning NULL in QGIS3.

**Comment by enricofer** [comment]
fixed https://github.com/enricofer/refFunctions/commit/5fca5aa12788520b1a0cfd2bd67bb87a470ec9c5 thanks for submission

**Comment by enricofer** [comment]
Migration to core: https://github.com/enricofer/refFunctions/wiki/Migration-to-core
