### ISSUE TITLE
invalid expression error in default value expression dialog

### ISSUE THREAD

**Issue by spaceof7** [enricofer/refFunctions#6]
I am not sure if this is a plugin bug or a QGIS bug, but I figured I should check here first.

I'm using QGIS 2.18.2-nightly on windows.  

I am having trouble when using the geomintersects() function in a "default value" expression.  
To reproduce:
open the field widget properties and open the default value expression dialog.
build an expression with the geomintersects function
I get the error, Eval Error: "'NoneType' object has no attribute 'intersects'"
close the expression dialog and type the expression directly in the default value box.
When entered here the expression works properly and you can see a preview.
The field calculator also handles the expression correctly.

Now that I think about it again I wonder if it is a QGIS bug after all.

Also, Thanks for your work, I find this plugin really useful.

**Comment by enricofer** [comment]
Assuming that it is a plugin issue I can't imagine where it is.
Anyway it's more likely to be a Qgis core issue.
