### ISSUE TITLE
geomdistance() error: invalid number of parameters

### ISSUE THREAD

**Issue by spaceof7** [enricofer/refFunctions#7]
when I try to use the geomdistance function I get an error about an invalid number of parameters.  Changing line 607 from 2 to 3 fixes the error.

**Comment by enricofer** [comment]
Thanks for submission. Would You try to send a Pull Request to fix the issue? I can point you how.

**Comment by spaceof7** [comment]
Sure thing, its been awhile but I think its all set.

**Comment by enricofer** [comment]
Migration to core: https://github.com/enricofer/refFunctions/wiki/Migration-to-core
